spring:
  messages:
    basename: i18n/exception
    encoding: UTF-8
  social:
    kakao:
      client_id: 75b16035c579ec5f76fd49e4cc1ea88c
      redirect: /social/login/kakao
      url:
        login: https://kauth.kakao.com/oauth/authorize
        token: https://kauth.kakao.com/oauth/token
        profile: https://kapi.kakao.com/v2/user/me
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgres://aztqncptoajzyw:46e62a0d10552d424cce91fde5734d281c89bbf350154fa95792118b0631548f@ec2-52-87-58-157.compute-1.amazonaws.com:5432/dddsktdf461hcf
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  jwt:
    secret: Hfa#24h!@$f9)1j
  url:
    base: https://pl-api-server.herokuapp.com